export interface PixelPetFrame {
  width: number;
  height: number;
  pixels: string[];
  palette: Record<string, string>;
}

export interface PixelPetFrames {
  id: string;
  name: string;
  idle: PixelPetFrame[];
  blink: PixelPetFrame[];
  happy: PixelPetFrame[];
}

// ============================================================
// Desktop-Pixel-Pet 迁移帧数据
// 来源：https://github.com/CanFlyhang/Desktop-Pixel-Pet (MIT License)
// 由 scripts/convert-desktop-pets.js 自动生成
// ============================================================
// --------------------------------------------------------
// 猫 — cat
// --------------------------------------------------------
const catPalette: Record<string, string> = {
  '.': 'transparent',
  'A': '#778899',
  'B': '#2f4f4f',
  'C': '#f0f8ff',
  'D': '#32cd32',
  'E': '#ffc0cb',
  'F': '#ffb6c1',
};

const catFrame0: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: catPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...........B........B...........',
    '.............BAB......BAB.......',
    '...........BAFAB....BAFAB.......',
    '..........BAAFAABBBBAAFAAB......',
    '..........BAAAAAAAAAAAAAAB......',
    '..........BAAAAAAAAAAAAAAB......',
    '..........BAABDDDDDDDDBAAB......',
    '..........BAABDDDDDDDDBAAB......',
    '..........BAABDDBBBBDDBAAB......',
    '...........BAAAAAAAAAAAAB.......',
    '...........BAAAAEAAEAAAAB.......',
    '.............BAAAACCAAAAB.......',
    '.............BAAAACCAAAAB.......',
    '...........BAAAACCCCAAAAB.......',
    '..........BAAAAACCCCAAAAAB......',
    '..........BAAAAACCCCAAAAAB......',
    '..........BAAAAACCCCAAAAAB......',
    '........BAAAAAACCCCAAAAAAB......',
    '........BAAAAAACCCCAAAAAAB......',
    '..........BBBBBBCCCCBBBBBB......',
    '.................BB..BB.........',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

const catFrame1: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: catPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...........B........B...........',
    '.............BAB......BAB.......',
    '...........BAFAB....BAFAB.......',
    '..........BAAFAABBBBAAFAAB......',
    '..........BAAAAAAAAAAAAAAB......',
    '..........BAAAAAAAAAAAAAAB......',
    '..........BAABDDDDDDDDBAAB......',
    '..........BAABBBBBBBBBBAAB......',
    '..........BAABDDBBBBDDBAAB......',
    '...........BAAAAAAAAAAAAB.......',
    '...........BAAAAEAAEAAAAB.......',
    '.............BAAAACCAAAAB.......',
    '.............BAAAACCAAAAB.......',
    '...........BAAAACCCCAAAAB.......',
    '..........BAAAAACCCCAAAAAB......',
    '..........BAAAAACCCCAAAAAB......',
    '.........BAAAAACCCCAAAAAB.B.....',
    '........BAAAAAACCCCAAAAAABB.....',
    '........BAAAAAACCCCAAAAAAB......',
    '..........BBBBBBCCCCBBBBBB......',
    '.................BB..BB.........',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

export const catFrames: PixelPetFrames = {
  id: 'cat',
  name: '猫',
  idle: [catFrame0, catFrame1],
  blink: [catFrame0],
  happy: [catFrame0],
};
// --------------------------------------------------------
// 狗 — dog
// --------------------------------------------------------
const dogPalette: Record<string, string> = {
  '.': 'transparent',
  'A': '#d2691e',
  'B': '#f5deb3',
  'C': '#8b4513',
  'D': '#000000',
  'E': '#323232',
  'F': '#ffb6c1',
  'G': '#dc143c',
};

const dogFrame0: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: dogPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '...........CC......CC...........',
    '.............CAAC....CAAC.......',
    '............CAAAAC..CAAAAC......',
    '............CAAAAAAAAAAAAC......',
    '..........CAAAAAAAAAAAAAAC......',
    '..........CAAAAAAAAAAAAAAC......',
    '.........CAAAABDDAADDBAAAAC.....',
    '.........CAAAABDDAADDBAAAAC.....',
    '.........CAAAABBBBBBBBAAAAC.....',
    '.........CAAAABBEBBEBBAAAAC.....',
    '..........CAAAABBFFBBAAAAC......',
    '..........CAAAAABBBBAAAAAC......',
    '............CAAAAAAAAAAAAC......',
    '.............CGGGGGGGGGGC.......',
    '...........CAAAAAAAAAAAAC.......',
    '..........CAAAAAAAAAAAAAAC......',
    '..........CAAAAAAAAAAAAAAC......',
    '..........CAAAABBBBBBAAAAC......',
    '........CAAAAABBBBBBAAAAAC......',
    '........CAAAAABBBBBBAAAAAC......',
    '........CAAAAABBBBBBAAAAAC......',
    '..........CCCCBBBBBBBBCCCC......',
    '..............CCCC..CCCC........',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

const dogFrame1: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: dogPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '...........CC......CC...........',
    '.............CAAC....CAAC.......',
    '............CAAAAC..CAAAAC......',
    '............CAAAAAAAAAAAAC......',
    '..........CAAAAAAAAAAAAAAC......',
    '..........CAAAAAAAAAAAAAAC......',
    '.........CAAAABDDAADDBAAAAC.....',
    '.........CAAAABDDAADDBAAAAC.....',
    '.........CAAAABBBBBBBBAAAAC.....',
    '.........CAAAABBEBBEBBAAAAC.....',
    '..........CAAAABBFFBBAAAAC......',
    '..........CAAAAABBFFAAAAAC......',
    '............CAAAAAFFAAAAAC......',
    '.............CGGGGGGGGGGC.......',
    '...........CAAAAAAAAAAAAC.......',
    '..........CAAAAAAAAAAAAAAC......',
    '..........CAAAAAAAAAAAAAAC......',
    '..........CAAAABBBBBBAAAAC......',
    '........CAAAAABBBBBBAAAAAC......',
    '........CAAAAABBBBBBAAAAAC......',
    '........CAAAAABBBBBBAAAAAC......',
    '..........CCCCBBBBBBBBCCCC......',
    '..............CCCC..CCCC........',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

export const dogFrames: PixelPetFrames = {
  id: 'dog',
  name: '狗',
  idle: [dogFrame0, dogFrame1],
  blink: [dogFrame0],
  happy: [dogFrame0],
};
// 龙 — dragon
// --------------------------------------------------------
const dragonPalette: Record<string, string> = {
  '.': 'transparent',
  'A': '#ffd700',
  'B': '#b8860b',
  'C': '#fffacd',
  'D': '#dc143c',
  'E': '#00fa9a',
  'F': '#ffffff',
  'G': '#2f2f2f',
};

const dragonFrame0: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: dragonPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...........GG.....GG............',
    '...............GDDG...GDDG......',
    '.............GDDAAG.GDDAAG......',
    '............GAAAAAEEAAAAAG......',
    '............GAAAAAAAAAAAAG......',
    '............GAAABAAAAABAAG......',
    '............GAAAFFAAAFFAAG......',
    '.............GAAAAAAAAAAAG......',
    '............GGAAAAAAAAAAAGG.....',
    '..........GDDAAAAAAAAAAADDG.....',
    '..........GDDAAAAAAAAAAADDG.....',
    '..........GAAAAAAAAAAAAAAAG.....',
    '..........GAAAAAAAAAAAAAAAG.....',
    '............GAAAAAAAAAAAAAG.....',
    '............GAAAAAAAAAAAAAG.....',
    '............GAAAGGGGGGAAAG......',
    '............GAAAG....GAAAG......',
    '..............GGG......GGG......',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

const dragonFrame1: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: dragonPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '........GG...........GG.........',
    '..........GDDG.........GDDG.....',
    '.........GDDAAG.......GDDAAG....',
    '.........GAAAAAEEAAAAAAAAAAG....',
    '.........GAAAAAAAAAAAAAAAAAG....',
    '.........GAAABAAAAAAAAABAAG.....',
    '.........GAAAFFAAAAAAAFFAAG.....',
    '..........GAAAAAAAAAAAAAAAG.....',
    '..........GAAAAAAAAAAAAAAAG.....',
    '..........GDDAAAAAAAAAAADDG.....',
    '..........GDDAAAAAAAAAAADDG.....',
    '..........GAAAAAAAAAAAAAAAG.....',
    '..........GAAAAAAAAAAAAAAAG.....',
    '............GAAAAAAAAAAAAAG.....',
    '............GAAAAAAAAAAAAAG.....',
    '............GAAAGGGGGGAAAG......',
    '............GAAAG....GAAAG......',
    '..............GGG......GGG......',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

export const dragonFrames: PixelPetFrames = {
  id: 'dragon',
  name: '龙',
  idle: [dragonFrame0, dragonFrame1],
  blink: [dragonFrame0],
  happy: [dragonFrame0],
};
// --------------------------------------------------------
// 兔子 — rabbit
// --------------------------------------------------------
const rabbitPalette: Record<string, string> = {
  '.': 'transparent',
  'A': '#ffffff',
  'B': '#dcdcdc',
  'C': '#ffc0cb',
  'D': '#000000',
  'E': '#ff69b4',
  'F': '#ff8c00',
  'G': '#228b22',
};

const rabbitFrame0: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: rabbitPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...........BB......BB...........',
    '.............BCCB....BCCB.......',
    '.............BCCB....BCCB.......',
    '.............BCCB....BCCB.......',
    '.............BCCB....BCCB.......',
    '.............BACCB..BACCB.......',
    '.............BAAAABBAAAAB.......',
    '...........BAAAAAAAAAAAAB.......',
    '...........BAAAAAAAAAAAAB.......',
    '...........BAAAADAADAAAAB.......',
    '...........BAAAADAADAAAAB.......',
    '.............BAAAAEEAAAAB.......',
    '.............BAAAAAAAAAAB.......',
    '...........BAAAAAAAAAAAAB.......',
    '..........BAAAAAAAAAAAAAAB......',
    '..........BAAAAAAAAAAAAAAB......',
    '........BAAAAAAAAAAAAAAAAB......',
    '........BAAAAAAAAAAAAAAAAB......',
    '........BAAAAAAAAAAAAAAAAB......',
    '..........BAAAAB....BAAAAB......',
    '..........BBBBBB....BBBBBB......',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

const rabbitFrame1: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: rabbitPalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...............BB...............',
    '.................BCCB...........',
    '.............BCCB.....BB........',
    '.............BCCB....BCCB.......',
    '.............BCCB....BCCB.......',
    '.............BACCB...BCCB.......',
    '.............BAAAABBBACCB.......',
    '...........BAAAAAAAAAAAAB.......',
    '...........BAAAAAAAAAAAAB.......',
    '...........BAAAADAADAAAAB.......',
    '...........BAAAADAADAAAAB.......',
    '.............BAAAAEEAAAAB.......',
    '.............BAAAAAAAAAAB.......',
    '...........BAAAAAAAAAAAAB.......',
    '..........BAAAAAAAAAAAAAAB......',
    '..........BAAAAAAAAAAAAAAB......',
    '........BAAAAAAAAAAAAAAAAB......',
    '........BAAAAAAAAAAAAAAAAB......',
    '........BAAAAAAAAAAAAAAAAB......',
    '..........BAAAAB....BAAAAB......',
    '..........BBBBBB....BBBBBB......',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

export const rabbitFrames: PixelPetFrames = {
  id: 'rabbit',
  name: '兔子',
  idle: [rabbitFrame0, rabbitFrame1],
  blink: [rabbitFrame0],
  happy: [rabbitFrame0],
};
// --------------------------------------------------------
// 特雷史莱姆 — trae_slime
// --------------------------------------------------------
const trae_slimePalette: Record<string, string> = {
  '.': 'transparent',
  'A': '#6495ed',
  'B': '#add8e6',
  'C': '#4169e1',
  'D': '#282828',
  'E': '#141414',
  'F': '#32cd32',
  'G': '#ffffff',
  'H': '#000000',
};

const trae_slimeFrame0: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: trae_slimePalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '............CCCCC...............',
    '...........CABBBC...............',
    '..........CABBBBBC..............',
    '..........CAHGABHC..............',
    '..........CABGABHC..............',
    '..........CAAAAAAC..............',
    '..........CCCCCCCC..............',
    '........DDDDDDDDDDDD............',
    '.......DEEEEEEEEEEEED...........',
    '.......DEFFEEFFEEFFED...........',
    '.......DEFFEEFFEEFFED...........',
    '.......DEEEEEEEEEEEED...........',
    '.......DDDDDDDDDDDDDD...........',
    '..........DD....DD..............',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

const trae_slimeFrame1: PixelPetFrame = {
  width: 32,
  height: 32,
  palette: trae_slimePalette,
  pixels: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '............CCCCC...............',
    '...........CABBBC...............',
    '..........CAHGABHC..............',
    '..........CABGABHC..............',
    '..........CAAAAAAC..............',
    '..........CCCCCCCC..............',
    '........DDDDDDDDDDDD............',
    '.......DEEEEEEEEEEEED...........',
    '.......DEFFEEFFEEFFED...........',
    '.......DEFFEEFFEEFFED...........',
    '.......DEEEEEEEEEEEED...........',
    '.......DDDDDDDDDDDDDD...........',
    '..........DD....DD..............',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};

export const trae_slimeFrames: PixelPetFrames = {
  id: 'trae_slime',
  name: '特雷史莱姆',
  idle: [trae_slimeFrame0, trae_slimeFrame1, trae_slimeFrame0, trae_slimeFrame1],
  blink: [trae_slimeFrame0],
  happy: [trae_slimeFrame0],
};

export const PIXEL_PET_CATALOG: Record<string, PixelPetFrames> = {
  cat: catFrames,
  dog: dogFrames,
  dragon: dragonFrames,
  rabbit: rabbitFrames,
  trae_slime: trae_slimeFrames,
};
