"""add user preferred_model

Revision ID: 88edf4721b21
Revises: 
Create Date: 2026-04-09 10:16:26.665142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88edf4721b21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 batch_alter_table 兼容 SQLite
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('preferred_model', sa.Enum('DEEPSEEK', 'KIMI', 'DOUBAO', 'OPENAI', name='aiprovider'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('preferred_model')
    # ### end Alembic commands ###
